# Generated by Django 4.2.16 on 2024-11-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='tipo',
            field=models.CharField(default='megasena', max_length=20),
        ),
    ]
