# Generated by Django 4.2.16 on 2024-11-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0002_aposta_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequenciaDezena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dezena', models.IntegerField()),
                ('frequencia', models.IntegerField()),
            ],
        ),
    ]
